import { defineField, defineType } from "sanity";
import { Settings } from "lucide-react";

export const siteSettings = defineType({
    name: "siteSettings",
    title: "Site Settings",
    type: "document",
    icon: Settings,
    groups: [
        { name: "content", title: "Content" },
        { name: "seo", title: "SEO" },
    ],
    fields: [
        defineField({
            name: "companyName",
            title: "Company Name",
            type: "string",
            group: "content",
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: "tagline",
            title: "Tagline",
            type: "localizedString",
            group: "content",
            initialValue: { en: "Tax strategy and financial clarity for business owners who want more.", es: "Estrategia fiscal y claridad financiera para propietarios de negocios que quieren más." },
        }),
        defineField({
            name: "logo",
            title: "Logo",
            type: "image",
            group: "content",
            options: { hotspot: true },
            fields: [
                {
                    name: "alt",
                    title: "Alternative Text",
                    type: "localizedString",
                },
            ],
        }),
        defineField({
            name: "logoAlt",
            title: "Logo for Dark Backgrounds",
            type: "image",
            group: "content",
            options: { hotspot: true },
            description: "Opcional. Use si el logo principal no se ve bien en encabezados/pies de página oscuros.",
        }),
        defineField({
            name: "phone",
            title: "Phone Number",
            type: "string",
            group: "content",
        }),
        defineField({
            name: "email",
            title: "Email Address",
            type: "string",
            group: "content",
        }),
        defineField({
            name: "address",
            title: "Office Address",
            type: "object",
            group: "content",
            fields: [
                { name: "street", type: "string", title: "Street Address" },
                { name: "city", type: "string", title: "City" },
                { name: "state", type: "string", title: "State" },
                { name: "zip", type: "string", title: "Zip Code" },
            ],
        }),
        defineField({
            name: "businessHours",
            title: "Business Hours",
            type: "array",
            group: "content",
            of: [
                {
                    type: "object",
                    fields: [
                        { name: "day", type: "localizedString", title: "Day" },
                        { name: "hours", type: "localizedString", title: "Hours" },
                    ],
                },
            ],
        }),
        defineField({
            name: "socialLinks",
            title: "Social Media Links",
            type: "object",
            group: "content",
            fields: [
                { name: "linkedin", type: "url", title: "LinkedIn URL" },
                { name: "facebook", type: "url", title: "Facebook URL" },
                { name: "youtube", type: "url", title: "YouTube URL" },
                { name: "instagram", type: "url", title: "Instagram URL" },
                { name: "twitter", type: "url", title: "X (Twitter) URL" },
            ],
        }),
        defineField({
            name: "ctaButtonText",
            title: "Header CTA Text",
            type: "localizedString",
            group: "content",
            initialValue: { en: "Book a Strategy Call", es: "Reserve Una Llamada de Estrategia" },
        }),
        defineField({
            name: "ctaButtonUrl",
            title: "Header CTA URL",
            type: "url",
            group: "content",
            validation: (Rule) => Rule.uri({ allowRelative: true, scheme: ["https", "http", "mailto", "tel"] }),
            initialValue: "https://calendly.com/",
        }),
        defineField({
            name: "seo",
            title: "Default SEO (Global Fallback)",
            type: "seo",
            group: "seo",
            description: "Metadatos predeterminados para páginas que no tienen su propio SEO definido.",
        }),
        defineField({
            name: "metaTitleSuffix",
            title: "Meta Title Suffix",
            type: "string",
            group: "seo",
            description: "Texto añadido al final del título de cada página (ej., ' | Union National Tax').",
            initialValue: " | Union National Tax",
        }),
        defineField({
            name: "metaTitleSeparator",
            title: "Meta Title Separator",
            type: "string",
            group: "seo",
            description: "El(los) carácter(es) entre el título de la página y el sufijo.",
            initialValue: " | ",
        }),
        defineField({
            name: "priceRange",
            title: "Price Range",
            type: "string",
            group: "content",
            description: "Rango de precio (ej., $, $$, $$$).",
            initialValue: "$$$",
        }),
        defineField({
            name: "foundingYear",
            title: "Founding Year",
            type: "number",
            group: "content",
            description: "El año en que se fundó la empresa.",
        }),
        defineField({
            name: "areaServed",
            title: "Area Served",
            type: "array",
            group: "content",
            of: [{ type: "localizedString" }],
            description: "Regiones atendidas (ej., Estados Unidos, Texas).",
            initialValue: [{ en: "United States", es: "Estados Unidos" }],
        }),
        defineField({
            name: "sameAs",
            title: "Same As (Directory Links)",
            type: "array",
            group: "content",
            of: [{ type: "url" }],
            description: "Enlaces a otros perfiles oficiales (Google Business, Yelp, etc.).",
        }),
        defineField({
            name: "copyrightText",
            title: "Copyright Text",
            type: "localizedString",
            group: "content",
            description: "El año se añadirá automáticamente.",
            initialValue: { en: "Union National Tax. All Rights Reserved.", es: "Union National Tax. Todos los Derechos Reservados." },
        }),
    ],
});
